/*
 * @author Valentin Simonov / http://va.lent.in/
 */

using TouchScript.Hit;
using TouchScript.InputSources;
using TouchScript.Layers;
using UnityEngine;

namespace TouchScript.Pointers
{
    /// <summary>
    /// <para>Representation of a pointer (touch, mouse) within TouchScript.</para>
    /// <para>An instance of this class is created when user touches the screen. A unique id is assigned to it which doesn't change throughout its life.</para>
    /// <para><b>Attention!</b> Do not store references to these objects beyond pointer's lifetime (i.e. when target finger is lifted off). These objects may be reused internally. Store unique ids instead.</para>
    /// </summary>
    public class Pointer
    {
        #region Constants

        /// <summary>
        /// Invalid pointer id.
        /// </summary>
        public const int INVALID_POINTER = -1;

        /// <summary>
        /// Indicates that this pointer is generated by script and is not mapped to any device input.
        /// </summary>
        public const uint FLAG_ARTIFICIAL = 1 << 0;

        /// <summary>
        /// Indicates a primary action, analogous to a left mouse button down.
        /// A <see cref="TouchPointer"/> or <see cref="ObjectPointer"/> has this flag set when it is in contact with the digitizer surface.
        /// A <see cref="PenPointer"/> has this flag set when it is in contact with the digitizer surface with no buttons pressed.
        /// A <see cref="MousePointer"/> has this flag set when the left mouse button is down.
        /// </summary>
        public const uint FLAG_FIRST_BUTTON = 1 << 1;

        /// <summary>
        /// Indicates a secondary action, analogous to a right mouse button down.
        /// A <see cref="TouchPointer"/> or <see cref="ObjectPointer"/> does not use this flag.
        /// A <see cref="PenPointer"/> has this flag set when it is in contact with the digitizer surface with the pen barrel button pressed.
        /// A <see cref="MousePointer"/> has this flag set when the right mouse button is down.
        /// </summary>
        public const uint FLAG_SECOND_BUTTON = 1 << 2;

        /// <summary>
        /// Analogous to a mouse wheel button down.
        /// A <see cref="TouchPointer"/> or <see cref="ObjectPointer"/> does not use this flag.
        /// A <see cref="PenPointer"/> does not use this flag.
        /// A <see cref="MousePointer"/> has this flag set when the mouse wheel button is down.
        /// </summary>
        public const uint FLAG_THIRD_BUTTON = 1 << 3;

        /// <summary>
        /// Indicates that this pointer is in contact with the surface. When this flag is not set, it indicates a hovering pointer.
        /// </summary>
        public const uint FLAG_INCONTACT = FLAG_FIRST_BUTTON | FLAG_SECOND_BUTTON | FLAG_THIRD_BUTTON;

        /// <summary>
        /// Pointer type.
        /// </summary>
        public enum PointerType
        {
            /// <summary>
            /// Touch.
            /// </summary>
            Touch,

            /// <summary>
            /// Mouse.
            /// </summary>
            Mouse,

            /// <summary>
            /// Pen.
            /// </summary>
            Pen,

            /// <summary>
            /// Object.
            /// </summary>
            Object
        }

        #endregion

        #region Public properties

        /// <summary>
        /// Internal unique pointer id.
        /// </summary>
        public int Id { get; private set; }

        /// <summary>
        /// Pointer type. See <see cref="PointerType"/>.
        /// </summary>
        public PointerType Type { get; protected set; }

        /// <summary>
        /// Original input source which created this pointer.
        /// <seealso cref="IInputSource"/>
        /// </summary>
        public IInputSource InputSource { get; private set; }

        /// <summary>
        /// <para>Current position in screen coordinates.</para>
        /// <para>Note: setting this property doesn't immediately change its value, the value actually changes during the next TouchManager update phase.</para>
        /// </summary>
        public Vector2 Position
        {
            get { return position; }
            set { newPosition = value; }
        }

        /// <summary>
        /// Previous <see cref="Position"/> (during last frame) in screen coordinates.
        /// </summary>
        public Vector2 PreviousPosition { get; private set; }

        /// <summary>
        /// <para>Gets or sets pointer flags: <see cref="FLAG_ARTIFICIAL"/>, <see cref="FLAG_FIRST_BUTTON"/>, <see cref="FLAG_SECOND_BUTTON"/>, <see cref="FLAG_THIRD_BUTTON"/>, <see cref="FLAG_INCONTACT"/>.</para>
        /// <para>Note: setting this property doesn't immediately change its value, the value actually changes during the next TouchManager update phase.</para>
        /// </summary>
        public uint Flags
        {
            get { return flags; }
            set { newFlags = value; }
        }

        /// <summary>
        /// Gets the previous value of <see cref="Flags"/>.
        /// </summary>
        public uint PreviousFlags { get; private set; }

        /// <summary>
        /// Projection parameters for the layer which created this pointer.
        /// </summary>
        public ProjectionParams ProjectionParams
        {
            get
            {
                if (pressData.Layer == null) return default(ProjectionParams);
                return pressData.Layer.GetProjectionParams(this);
            }
        }

        #endregion

        #region Private variables

        private int refCount = 0;
        private Vector2 position, newPosition;
        private uint flags, newFlags;
        private HitData pressData, overData;
        private bool overDataIsDirty = true;

        #endregion

        #region Public methods

        public HitData GetOverData(bool forceRecalculate = false)
        {
            if (overDataIsDirty || forceRecalculate)
            {
                TouchManager.Instance.GetHitTarget(position, out overData);
                overDataIsDirty = false;
            }
            return overData;
        }

        public HitData GetPressData()
        {
            return pressData;
        }

        /// <summary>
        /// Copies values from <see cref="target"/>.
        /// </summary>
        /// <param name="target">The target pointer to copy values from.</param>
        public virtual void CopyFrom(Pointer target)
        {
            Type = target.Type;
            flags = target.flags;
            newFlags = target.newFlags;
            PreviousFlags = target.PreviousFlags;
            position = target.position;
            newPosition = target.newPosition;
            PreviousPosition = target.PreviousPosition;
        }

        /// <inheritdoc />
        public override bool Equals(object other)
        {
            return Equals(other as Pointer);
        }

        /// <inheritdoc />
        public bool Equals(Pointer other)
        {
            if (other == null)
                return false;

            return Id == other.Id;
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            return Id;
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="Pointer"/> class.
        /// </summary>
        public Pointer(IInputSource input)
        {
            Type = PointerType.Touch;
            InputSource = input;
            INTERNAL_Reset();
        }

        #endregion

        #region Internal methods

        internal virtual void INTERNAL_Init(int id)
        {
            Id = id;
            PreviousPosition = position = newPosition;
            PreviousFlags = flags = newFlags;
        }

        internal virtual void INTERNAL_Reset()
        {
            Id = INVALID_POINTER;
            INTERNAL_ClearTargetData();
            position = newPosition = PreviousPosition = Vector2.zero;
            flags = newFlags = PreviousFlags = 0;
        }

        internal virtual void INTERNAL_FrameStarted()
        {
            PreviousPosition = position;
            position = newPosition;
            PreviousFlags = flags;
            flags = newFlags;

            overDataIsDirty = true;
        }

        internal void INTERNAL_Retain()
        {
            refCount++;
        }

        internal int INTERNAL_Release()
        {
            return --refCount;
        }

        internal void INTERNAL_SetTargetData(HitData data)
        {
            pressData = data;
        }

        internal void INTERNAL_ClearTargetData()
        {
            pressData = default(HitData);
            refCount = 0;
        }

        #endregion
    }
}